[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/webhook"
  to = "/.netlify/functions/whatsapp-webhook"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"